spring.application.name=CampusScoreManager
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/smxy_class
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis-plus.configuration.map-underscore-to-camel-case=false

shiro.auth.anon-urls[0]=/
shiro.auth.anon-urls[1]=/api/v1/user/login
shiro.auth.anon-urls[2]=/api/v1/user/logout
shiro.auth.use-default-user-login-model-cache=true
